#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ast
import json
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str((ROOT / "tools").resolve()))
import run_ast_merger_gpt_batches as base  # noqa: E402

META = ROOT / "codeforces_data" / "problems_meta.json"
STATEMENTS = ROOT / "codeforces_data" / "statements"
SRC = ROOT / "sonnet_gen"
OUT = ROOT / "ast_merger_sonnet"
PYTHON = ROOT / ".venv" / "bin" / "python"
if not PYTHON.exists():
    PYTHON = Path(sys.executable)

CODE_BLOCK = re.compile(r"```(?:python|py)?\s*\n(.*?)```", re.I | re.S)
CLAUSE = re.compile(r"^\s*#\s*CLAUSE:\s*([a-z][a-z0-9_]{2,40})\s*$", re.I | re.M)
BAD = re.compile(r"(?i)(generated by|gpt|todo\b|fixme\b|placeholder\b|stub\b|not\s+implemented|implement\s+me)")


def pid(p: dict) -> str:
    return f"{p['contestId']}{p['index']}"


def statement(problem: dict) -> str:
    path = STATEMENTS / f"{problem['contestId']}_{problem['index']}.json"
    data = json.loads(path.read_text(errors="replace")) if path.exists() else {}
    samples = "\n\n".join(
        f"Sample {i} input:\n{s.get('input','')}\nSample {i} output:\n{s.get('output','')}"
        for i, s in enumerate(data.get("samples", []), 1)
    )
    return f"""Problem id: {pid(problem)}
Title: {data.get('title') or problem.get('name')}
Rating: {problem.get('rating','unknown')}
Tags: {', '.join(problem.get('tags', []))}

Statement:
{data.get('statement','')}

Input:
{data.get('input_spec','')}

Output:
{data.get('output_spec','')}

Samples:
{samples or '(none)'}
"""


def prompt(problem: dict, seed: str) -> str:
    return f"""Write exactly four complete Python 3 programs for this Codeforces problem.

Use these exact clause markers in this exact order in every program:
# CLAUSE: setup_environment
# CLAUSE: solve_logic
# CLAUSE: finish_program

Existing reference implementation, for correctness reference only:
```python
{seed}
```

Requirements:
- Keep same input/output behavior.
- Make at least two candidates meaningfully different in implementation structure from reference when easy:
  loop form, helper factoring, data structure choice, preprocessing shape, boundary-case layout, output assembly.
- Do not use exec, compile, eval, base64, subprocess, filesystem, network, or comments except CLAUSE markers.
- Do not mention any model/tool/source/generation.
- No TODO/pass/placeholders.
- Return exactly four fenced python code blocks and nothing else.

{statement(problem)}
"""


def compile_ok(path: Path) -> tuple[bool, str]:
    r = subprocess.run([str(PYTHON), "-m", "py_compile", str(path)], text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return r.returncode == 0, r.stderr[-1000:]


def markers(code: str) -> list[str]:
    return [m.group(1).lower() for m in CLAUSE.finditer(code)]


def backup(pdir: Path, broot: Path) -> None:
    if not pdir.exists():
        return
    dest = broot / pdir.name
    if dest.exists():
        return
    dest.mkdir(parents=True, exist_ok=True)
    for p in pdir.iterdir():
        if p.is_file():
            shutil.copy2(p, dest / p.name)


def ensure_seed_clauses(seed: str) -> str:
    if markers(seed):
        return seed if seed.endswith("\n") else seed + "\n"
    return "# CLAUSE: setup_environment\nimport sys\n\n# CLAUSE: solve_logic\n" + seed.strip() + "\n\n# CLAUSE: finish_program\nRESULT_SENTINEL = None\n"


def valid(code: str) -> tuple[bool, str]:
    if BAD.search(code):
        return False, "bad text"
    if markers(code) != ["setup_environment", "solve_logic", "finish_program"]:
        return False, f"bad markers {markers(code)}"
    try:
        ast.parse(code)
    except Exception as exc:
        return False, str(exc)
    return True, ""


def run_one(problem: dict, model: str, timeout: int, broot: Path) -> dict:
    problem_id = pid(problem)
    seed_path = SRC / problem_id / "solution.py"
    if not seed_path.exists():
        return {"problem": problem_id, "status": "missing-seed"}
    seed = seed_path.read_text(errors="replace")
    cand1 = ensure_seed_clauses(seed)
    try:
        raw = base.call_codex(prompt(problem, seed), model, timeout)
        blocks = [b.strip() + "\n" for b in CODE_BLOCK.findall(raw)]
        if len(blocks) != 4:
            raise RuntimeError(f"expected 4 blocks got {len(blocks)}")
        codes = [cand1] + blocks
        for i, code in enumerate(codes, 1):
            ok, err = valid(code)
            if not ok:
                raise RuntimeError(f"candidate {i}: {err}")
    except Exception as exc:
        (OUT / problem_id).mkdir(parents=True, exist_ok=True)
        (OUT / problem_id / "deepen_error.txt").write_text(str(exc))
        return {"problem": problem_id, "status": "failed", "error": str(exc)[-500:]}

    pdir = OUT / problem_id
    backup(pdir, broot)
    pdir.mkdir(parents=True, exist_ok=True)
    for i, code in enumerate(codes, 1):
        path = pdir / f"candidate_{i}.py"
        path.write_text(code)
        ok, err = compile_ok(path)
        if not ok:
            return {"problem": problem_id, "status": "compile-failed", "candidate": i, "error": err}

    base.OUT = OUT
    rec = base.merge_problem(problem_id, 120)
    merged = pdir / "merged.py"
    ok, _ = compile_ok(merged)
    if not ok:
        merged.write_text(codes[0])
        rec["status"] = "candidate1-fallback"
    return {"problem": problem_id, "status": "generated", "merge": rec.get("status"), "confidence": rec.get("confidence")}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=247)
    ap.add_argument("--model", default="gpt-5.5")
    ap.add_argument("--timeout", type=int, default=1200)
    ap.add_argument("--fail-stop", type=int, default=3)
    args = ap.parse_args()
    meta = json.loads(META.read_text())
    report_path = OUT / "sonnet_deepen_reverse_report.json"
    done = set()
    if report_path.exists():
        try:
            done = {r["problem"] for r in json.loads(report_path.read_text()).get("rows", [])}
        except Exception:
            done = set()
    targets = []
    for pos, problem in reversed(list(enumerate(meta, 1))):
        problem_id = pid(problem)
        if problem_id in done:
            continue
        if (OUT / problem_id).exists():
            targets.append((pos, problem))
        if len(targets) >= args.limit:
            break
    broot = OUT / f".backup_deepen_reverse_{time.strftime('%Y%m%d_%H%M%S')}"
    broot.mkdir(parents=True, exist_ok=True)
    old_rows = []
    if report_path.exists():
        try:
            old_rows = json.loads(report_path.read_text()).get("rows", [])
        except Exception:
            old_rows = []
    rows = old_rows
    fails = 0
    for n, (pos, problem) in enumerate(targets, 1):
        row = run_one(problem, args.model, args.timeout, broot)
        row["position"] = pos
        rows.append(row)
        report_path.write_text(json.dumps({"rows": rows}, indent=2))
        print(f"[deepen {n:03d}/{len(targets):03d}] {pos} {row['problem']}: {row['status']} merge={row.get('merge')} conf={row.get('confidence')}", flush=True)
        fails = fails + 1 if row["status"] != "generated" else 0
        if fails >= args.fail_stop:
            print("stopping: repeated failures", flush=True)
            break
    print(f"report={report_path}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
