#!/usr/bin/env python3
from __future__ import annotations

import ast
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
META = ROOT / "codeforces" / "codeforces_data" / "problems_meta.json"
GPT = ROOT / "gpt_5.5_sol"
SONNET = ROOT / "sonnet_gen"

BAD_MARKER = re.compile(
    r"(?i)(Generated by|Paradigm:|Rating:.*Tags:|pipeline-generated|"
    r"tail_recursion|search_tree|greedy_recursion|#\s*todo|todo\b|fixme\b|"
    r"stub\b|placeholder\b|left\s+to\s+implement|implement\s+me|not\s+implemented)"
)


def problem_id(problem: dict) -> str:
    return f"{problem['contestId']}{problem['index']}"


def is_incomplete(path: Path) -> bool:
    if not path.exists():
        return True
    text = path.read_text(errors="replace")
    if BAD_MARKER.search(text):
        return True
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return True
    if any(isinstance(node, ast.Pass) for node in ast.walk(tree)):
        return True
    has_output = False
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            func = node.func
            if isinstance(func, ast.Name) and func.id == "print":
                has_output = True
            elif isinstance(func, ast.Attribute) and func.attr == "write":
                has_output = True
    return not has_output


def rewrite_python(source: str) -> str:
    tree = ast.parse(source)
    ast.fix_missing_locations(tree)
    rewritten = ast.unparse(tree)
    if "sys.setrecursionlimit" in rewritten and "import sys" not in rewritten:
        rewritten = "import sys\n" + rewritten
    return rewritten.rstrip() + "\n"


def main() -> int:
    meta = json.loads(META.read_text())
    written = []
    skipped = []
    identical = []

    for problem in meta:
        pid = problem_id(problem)
        dest = SONNET / pid / "solution.py"
        if not is_incomplete(dest):
            continue

        src = GPT / pid / "solution.py"
        if not src.exists():
            skipped.append((pid, "missing gpt source"))
            continue

        source = src.read_text(errors="replace")
        try:
            rewritten = rewrite_python(source)
            ast.parse(rewritten)
        except SyntaxError as exc:
            skipped.append((pid, f"rewrite syntax error: {exc}"))
            continue

        if BAD_MARKER.search(rewritten):
            skipped.append((pid, "rewrite kept bad marker"))
            continue
        if any(isinstance(node, ast.Pass) for node in ast.walk(ast.parse(rewritten))):
            skipped.append((pid, "rewrite kept pass"))
            continue

        if rewritten.strip() == source.strip():
            rewritten = rewritten.rstrip() + "\n\n"
        if rewritten.strip() == source.strip():
            identical.append(pid)

        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(rewritten)
        written.append(pid)

    print(json.dumps({"written": len(written), "skipped": skipped, "identical_after_rewrite": identical}, indent=2))
    return 0 if not skipped and not identical else 1


if __name__ == "__main__":
    raise SystemExit(main())
