#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
import sys
import tempfile
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
META = ROOT / "codeforces" / "codeforces_data" / "problems_meta.json"
STATEMENTS = ROOT / "codeforces" / "codeforces_data" / "statements"
SONNET = ROOT / "sonnet_gen"
GPT = ROOT / "gpt_5.5_sol"
PROGRESS = ROOT / "logs" / "sonnet_scratch_rewrite_progress.json"

CODE_BLOCK = re.compile(r"```(?:python|py)?\s*\n(.*?)```", re.DOTALL | re.I)
BAD_TEXT = re.compile(
    r"(?i)(Generated by|Paradigm:|Rating:.*Tags:|pipeline-generated|"
    r"tail_recursion|search_tree|greedy_recursion|#\s*todo|todo\b|"
    r"fixme\b|stub\b|placeholder\b|left\s+to\s+implement|"
    r"implement\s+me|not\s+implemented)"
)
PRINT_LOCK = threading.Lock()

STYLE_EXAMPLES = ["1693B", "2084A", "364A", "1220B", "1574C", "1508B"]


def problem_id(problem: dict) -> str:
    return f"{problem['contestId']}{problem['index']}"


def load_meta() -> list[dict]:
    return json.loads(META.read_text())


def compile_ok(path: Path) -> tuple[bool, str]:
    result = subprocess.run(
        [sys.executable, "-m", "py_compile", str(path)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    return result.returncode == 0, result.stderr.strip()[:700]


def has_real_output(code: str) -> bool:
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return False
    if any(isinstance(node, ast.Pass) for node in ast.walk(tree)):
        return False
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            func = node.func
            if isinstance(func, ast.Name) and func.id == "print":
                return True
            if isinstance(func, ast.Attribute) and func.attr == "write":
                return True
    return False


def target_ids(problems: list[dict]) -> list[str]:
    out = []
    for problem in problems:
        name = problem_id(problem)
        directory = SONNET / name
        if not (directory / "raw_attempt1.md").exists():
            out.append(name)
    for name in ("1042F", "639B"):
        if name not in out:
            out.append(name)
    return out


def load_done() -> set[str]:
    if not PROGRESS.exists():
        return set()
    try:
        data = json.loads(PROGRESS.read_text())
    except Exception:
        return set()
    return {name for name, rec in data.get("problems", {}).items() if rec.get("status") == "ok"}


def record(name: str, status: str, **extra: object) -> None:
    with PRINT_LOCK:
        try:
            data = json.loads(PROGRESS.read_text()) if PROGRESS.exists() else {}
        except Exception:
            data = {}
        problems = data.setdefault("problems", {})
        problems[name] = {"status": status, "updated": time.strftime("%Y-%m-%d %H:%M:%S"), **extra}
        PROGRESS.parent.mkdir(parents=True, exist_ok=True)
        tmp = PROGRESS.with_suffix(".tmp")
        tmp.write_text(json.dumps(data, indent=2, sort_keys=True))
        tmp.replace(PROGRESS)


def statement_for(problem: dict) -> str:
    path = STATEMENTS / f"{problem['contestId']}_{problem['index']}.json"
    data = json.loads(path.read_text())
    samples = "\n\n".join(
        f"Sample {i} input:\n{sample.get('input', '')}\nSample {i} output:\n{sample.get('output', '')}"
        for i, sample in enumerate(data.get("samples", []), 1)
    )
    return f"""Problem id: {problem_id(problem)}
Title: {data.get("title") or problem["name"]}
Rating: {problem.get("rating", "unknown")}
Tags: {", ".join(problem.get("tags", []))}
Time limit: {data.get("time_limit", "unknown")}
Memory limit: {data.get("mem_limit", "unknown")}

Statement:
{data.get("statement", "")}

Input:
{data.get("input_spec", "")}

Output:
{data.get("output_spec", "")}

Samples:
{samples or "(none)"}
"""


def style_guide() -> str:
    pieces = []
    for name in STYLE_EXAMPLES:
        path = SONNET / name / "solution.py"
        if path.exists():
            text = path.read_text(errors="replace").strip()
            pieces.append(f"Example {name}:\n{text[:1800]}")
    return "\n\n".join(pieces)


def prompt(problem: dict) -> str:
    return f"""You are writing a fresh Codeforces Python solution in a Sonnet-like style.

Important constraints:
- Solve only from the problem statement below.
- Do not inspect, copy, paraphrase, or rely on any GPT-5.5 solution.
- Derive the algorithm yourself from the statement and constraints.
- Write complete runnable Python 3 / PyPy 3 code only.
- Use stdin/stdout.
- No TODOs, stubs, placeholders, generic fallback logic, metadata headers, ratings, tags, or explanation text.
- Prefer the style shown in the Sonnet examples: direct functions, clear variable names, simple input parsing, modest comments only when helpful.
- Reply with exactly one fenced python code block.

Sonnet style examples:
{style_guide()}

Problem to solve:
{statement_for(problem)}
"""


def extract_code(text: str) -> str:
    blocks = CODE_BLOCK.findall(text)
    if not blocks:
        raise RuntimeError("no fenced python code block")
    return max(blocks, key=len).strip() + "\n"


def different_from_gpt(name: str, code: str) -> bool:
    gpt_path = GPT / name / "solution.py"
    if not gpt_path.exists():
        return True
    return code.strip() != gpt_path.read_text(errors="replace").strip()


def generate_one(problem: dict, model: str, timeout: int, attempts: int) -> dict:
    name = problem_id(problem)
    dest_dir = SONNET / name
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / "solution.py"
    last_error = ""

    for attempt in range(1, attempts + 1):
        with tempfile.NamedTemporaryFile(prefix=f"sonnet_scratch_{name}_", suffix=".md", delete=False) as fh:
            last_msg = Path(fh.name)
        try:
            result = subprocess.run(
                [
                    "codex",
                    "exec",
                    "--model",
                    model,
                    "--cd",
                    str(ROOT),
                    "--sandbox",
                    "read-only",
                    "--dangerously-bypass-approvals-and-sandbox",
                    "--output-last-message",
                    str(last_msg),
                    prompt(problem),
                ],
                cwd=str(ROOT),
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=timeout,
                check=False,
            )
            if result.returncode != 0:
                detail = (result.stderr.strip() or result.stdout.strip())[-1200:]
                raise RuntimeError(f"codex exit {result.returncode}: {detail}")
            code = extract_code(last_msg.read_text(errors="replace"))
            if BAD_TEXT.search(code):
                raise RuntimeError("bad marker in generated code")
            if not has_real_output(code):
                raise RuntimeError("generated code has pass/no output/syntax issue")
            if not different_from_gpt(name, code):
                raise RuntimeError("generated code exactly matches gpt_5.5 solution")

            tmp = dest.with_suffix(".scratch_tmp.py")
            tmp.write_text(code)
            ok, err = compile_ok(tmp)
            if not ok:
                tmp.unlink(missing_ok=True)
                raise RuntimeError(f"compile error: {err}")
            tmp.replace(dest)
            (dest_dir / "raw_scratch_rewrite.md").write_text(last_msg.read_text(errors="replace"))
            record(name, "ok", attempt=attempt, bytes=len(code))
            return {"problem": name, "status": "ok", "attempt": attempt, "bytes": len(code)}
        except Exception as exc:
            last_error = str(exc)
            record(name, "pending", attempt=attempt, error=last_error[:1200])
            time.sleep(min(10 * attempt, 45))
        finally:
            last_msg.unlink(missing_ok=True)

    record(name, "failed", error=last_error[:1200])
    return {"problem": name, "status": "failed", "error": last_error}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default="gpt-5.5")
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--attempts", type=int, default=3)
    parser.add_argument("--timeout", type=int, default=900)
    parser.add_argument("--only", nargs="*")
    parser.add_argument("--limit", type=int)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    problems = load_meta()
    by_id = {problem_id(problem): problem for problem in problems}
    targets = args.only or target_ids(problems)
    if args.limit:
        targets = targets[: args.limit]
    done = set() if args.force else load_done()
    targets = [name for name in targets if name not in done]

    print(f"scratch targets: {len(targets)}; workers={args.workers}; model={args.model}", flush=True)
    if not targets:
        return 0

    failed = []
    complete = 0
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = [pool.submit(generate_one, by_id[name], args.model, args.timeout, args.attempts) for name in targets]
        for future in as_completed(futures):
            rec = future.result()
            complete += 1
            if rec["status"] != "ok":
                failed.append(rec["problem"])
            print(f"progress: {complete}/{len(targets)} scratch-written; {rec['problem']}: {rec['status']}", flush=True)

    if failed:
        print("failed:", " ".join(failed), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
