#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
import sys
import tempfile
import time
import urllib.request
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
META = ROOT / "codeforces" / "codeforces_data" / "problems_meta.json"
STATEMENTS = ROOT / "codeforces" / "codeforces_data" / "statements"
OUT = ROOT / "ast_merger_gpt_5.5_wrongs"
SUBMISSIONS = ROOT / "submissions"
LOGS = ROOT / "logs"
SUBMITTER = ROOT / "scripts" / "submit_batch_codeforces.mjs"
MERGER = ROOT / "ast_merger_lang_agnostic" / "evaluate_clauses.py"
PROGRESS = OUT / "progress.json"
PYTHON = ROOT / ".venv" / "bin" / "python"
if not PYTHON.exists():
    PYTHON = Path(sys.executable)

CODE_BLOCK = re.compile(r"```(?:python|py)?\s*\n(.*?)```", re.DOTALL | re.I)
BAD_TEXT = re.compile(
    r"(?i)(Generated by|Paradigm:|Rating:.*Tags:|pipeline-generated|"
    r"#\s*todo|todo\b|fixme\b|stub\b|placeholder\b|left\s+to\s+implement|"
    r"implement\s+me|not\s+implemented)"
)
BAD_VERDICTS = {
    "WRONG_ANSWER",
    "TIME_LIMIT_EXCEEDED",
    "RUNTIME_ERROR",
    "MEMORY_LIMIT_EXCEEDED",
    "IDLENESS_LIMIT_EXCEEDED",
    "COMPILATION_ERROR",
    "PARTIAL",
}
LABELS = {
    "OK": "Accepted",
    "WRONG_ANSWER": "Wrong answer",
    "TIME_LIMIT_EXCEEDED": "Time limit exceeded",
    "MEMORY_LIMIT_EXCEEDED": "Memory limit exceeded",
    "RUNTIME_ERROR": "Runtime error",
    "COMPILATION_ERROR": "Compilation error",
    "IDLENESS_LIMIT_EXCEEDED": "Idleness limit exceeded",
    "PARTIAL": "Partial",
    "TESTING": "Testing",
}


def problem_id(problem: dict) -> str:
    return f"{problem['contestId']}{problem['index']}"


def load_progress() -> dict:
    if not PROGRESS.exists():
        return {"problems": {}}
    try:
        return json.loads(PROGRESS.read_text())
    except Exception:
        return {"problems": {}}


def save_progress(data: dict) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    tmp = PROGRESS.with_suffix(".tmp")
    tmp.write_text(json.dumps(data, indent=2, sort_keys=True))
    tmp.replace(PROGRESS)


def mark(pid: str, status: str, **extra: object) -> None:
    data = load_progress()
    data.setdefault("problems", {})[pid] = {
        "status": status,
        "updated": time.strftime("%Y-%m-%d %H:%M:%S"),
        **extra,
    }
    save_progress(data)


def compile_ok(path: Path) -> tuple[bool, str]:
    res = subprocess.run(
        [str(PYTHON), "-m", "py_compile", str(path)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    return res.returncode == 0, res.stderr.strip()[-1000:]


def style_signature(code: str) -> tuple[int, int, int]:
    tree = ast.parse(code)
    funcs = sum(isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) for n in ast.walk(tree))
    classes = sum(isinstance(n, ast.ClassDef) for n in ast.walk(tree))
    imports = sum(isinstance(n, (ast.Import, ast.ImportFrom)) for n in tree.body)
    return funcs, classes, imports


def statement_for(problem: dict) -> str:
    path = STATEMENTS / f"{problem['contestId']}_{problem['index']}.json"
    data = json.loads(path.read_text())
    samples = "\n\n".join(
        f"Sample {i} input:\n{s.get('input', '')}\nSample {i} output:\n{s.get('output', '')}"
        for i, s in enumerate(data.get("samples", []), 1)
    )
    return f"""Problem id: {problem_id(problem)}
Title: {data.get("title") or problem["name"]}
Rating: {problem.get("rating", "unknown")}
Tags: {", ".join(problem.get("tags", []))}
Time limit: {data.get("time_limit", "unknown")}
Memory limit: {data.get("mem_limit", "unknown")}

Statement:
{data.get("statement", "")}

Input:
{data.get("input_spec", "")}

Output:
{data.get("output_spec", "")}

Samples:
{samples or "(none)"}
"""


def generation_prompt(problem: dict) -> str:
    return f"""Write five independent Python 3 / PyPy 3 solutions for this Codeforces problem.

Important ensemble constraint:
- All five programs must use the same high-level algorithmic paradigm and the same rough modularity.
- Prefer one procedural `solve()` plus small helpers only when genuinely needed.
- Differences should be local implementation choices, naming, boundary handling, and expression structure.
- Do not make one recursive, one class-based, one brute-force, one optimized, etc.
- Do not include explanations or comments.

Correctness constraint:
- Each program must be complete and intended to pass the official constraints.
- Standard input only, standard output only.
- No placeholders, TODOs, generic fallback logic, or guessed echo/sum behavior.

Return exactly five fenced python code blocks, nothing else.

{statement_for(problem)}
"""


def extract_five(text: str) -> list[str]:
    blocks = [b.strip() + "\n" for b in CODE_BLOCK.findall(text)]
    if len(blocks) != 5:
        raise RuntimeError(f"expected 5 python blocks, got {len(blocks)}")
    return blocks


def validate_candidate(path: Path, code: str) -> tuple[bool, str]:
    if BAD_TEXT.search(code):
        return False, "bad marker"
    path.write_text(code)
    ok, err = compile_ok(path)
    if not ok:
        return False, err
    try:
        style_signature(code)
    except Exception as exc:
        return False, f"ast parse failed: {exc}"
    return True, ""


def statement_samples_for_pid(pid: str) -> list[dict]:
    match = re.match(r"^(\d+)([A-Z]\d*)$", pid)
    if not match:
        return []
    path = STATEMENTS / f"{match.group(1)}_{match.group(2)}.json"
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text())
    except Exception:
        return []
    return [s for s in data.get("samples", []) if "input" in s and "output" in s]


def run_candidate_on_samples(path: Path, samples: list[dict], timeout: int = 5) -> dict:
    if not samples:
        return {"passed": 0, "total": 0, "ok": True, "reason": "no samples"}

    ok, err = compile_ok(path)
    if not ok:
        return {"passed": 0, "total": len(samples), "ok": False, "reason": err or "compile failed"}

    passed = 0
    for index, sample in enumerate(samples, 1):
        try:
            res = subprocess.run(
                [str(PYTHON), str(path)],
                input=sample.get("input") or "",
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=timeout,
                check=False,
            )
        except subprocess.TimeoutExpired:
            return {
                "passed": passed,
                "total": len(samples),
                "ok": False,
                "reason": f"sample {index} timed out",
            }

        got = res.stdout.strip()
        expected = (sample.get("output") or "").strip()
        if res.returncode != 0:
            return {
                "passed": passed,
                "total": len(samples),
                "ok": False,
                "reason": f"sample {index} runtime error",
            }
        if got != expected:
            return {
                "passed": passed,
                "total": len(samples),
                "ok": False,
                "reason": f"sample {index} wrong answer",
            }
        passed += 1

    return {"passed": passed, "total": len(samples), "ok": True, "reason": "passed samples"}


def generate_candidates(problem: dict, model: str, timeout: int, force: bool) -> dict:
    pid = problem_id(problem)
    pdir = OUT / pid
    pdir.mkdir(parents=True, exist_ok=True)
    existing = [pdir / f"candidate_{i}.py" for i in range(1, 6)]
    if not force and all(p.exists() for p in existing):
        try:
            signatures = [style_signature(p.read_text()) for p in existing]
            if len(set(signatures)) <= 2:
                mark(pid, "generated", signatures=[list(x) for x in signatures])
                return {"problem": pid, "status": "generated", "cached": True}
        except Exception:
            pass

    last_error = ""
    for attempt in range(1, 4):
        with tempfile.NamedTemporaryFile(prefix=f"top5_{pid}_", suffix=".md", delete=False) as fh:
            last_msg = Path(fh.name)
        try:
            res = subprocess.run(
                [
                    "codex",
                    "exec",
                    "--model",
                    model,
                    "--cd",
                    str(ROOT),
                    "--sandbox",
                    "read-only",
                    "--dangerously-bypass-approvals-and-sandbox",
                    "--output-last-message",
                    str(last_msg),
                    generation_prompt(problem),
                ],
                cwd=str(ROOT),
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=timeout,
                check=False,
            )
            if res.returncode != 0:
                detail = (res.stderr.strip() or res.stdout.strip())[-1200:]
                raise RuntimeError(f"codex exit {res.returncode}: {detail}")
            blocks = extract_five(last_msg.read_text(errors="replace"))
            signatures = []
            seen = set()
            for i, code in enumerate(blocks, 1):
                if code.strip() in seen:
                    raise RuntimeError("duplicate candidate block")
                seen.add(code.strip())
                dest = pdir / f"candidate_{i}.py"
                ok, err = validate_candidate(dest, code)
                if not ok:
                    raise RuntimeError(f"candidate {i}: {err}")
                signatures.append(style_signature(code))
            if len(set(signatures)) > 2:
                raise RuntimeError(f"candidate modularity differs too much: {signatures}")
            raw = pdir / "top5_raw.md"
            raw.write_text(last_msg.read_text(errors="replace"))
            mark(pid, "generated", attempt=attempt, signatures=[list(x) for x in signatures])
            return {"problem": pid, "status": "generated", "attempt": attempt}
        except Exception as exc:
            last_error = str(exc)
            mark(pid, "generate-pending", attempt=attempt, error=last_error[:1000])
            time.sleep(5 * attempt)
        finally:
            last_msg.unlink(missing_ok=True)
    mark(pid, "generate-failed", error=last_error[:1000])
    return {"problem": pid, "status": "generate-failed", "error": last_error}


def build_uast_input(pid: str) -> Path:
    pdir = OUT / pid
    samples = statement_samples_for_pid(pid)
    passing = []
    all_candidates = []
    sample_results = []
    for i in range(1, 6):
        path = pdir / f"candidate_{i}.py"
        all_candidates.append((i, path.read_text()))
        result = run_candidate_on_samples(path, samples)
        result = {"candidate": i, **result}
        sample_results.append(result)
        if result["ok"]:
            passing.append((i, path.read_text()))
    selected = passing if passing or not samples else all_candidates
    sample_gate = "passing_only"
    if not samples:
        sample_gate = "no_samples_all_candidates"
    elif not passing:
        sample_gate = "fallback_all_candidates"

    (pdir / "sample_filter.json").write_text(json.dumps({
        "samples": len(samples),
        "selectedCandidates": [i for i, _ in selected],
        "passingCandidates": [i for i, _ in passing],
        "sampleGate": sample_gate,
        "results": sample_results,
    }, indent=2))

    payload = {
        "programs": [
            {
                "id": f"P{i}",
                "clauses": [
                    {
                        "clause_id": "program",
                        "signature": "python_module",
                        "code": source if source.endswith("\n") else source + "\n",
                    }
                ],
            }
            for i, source in selected
        ]
    }
    out = pdir / "uast_input.json"
    out.write_text(json.dumps(payload, indent=2))
    return out


def merge_one(pid: str, timeout: int) -> dict:
    pdir = OUT / pid
    merged = pdir / "merged.py"
    trees = pdir / "trees.txt"
    log = pdir / "merge.log"
    started = time.monotonic()
    try:
        inp = build_uast_input(pid)
    except Exception as exc:
        elapsed = round(time.monotonic() - started, 2)
        message = str(exc)
        log.write_text(message + "\n")
        mark(pid, "merge-failed", error=message[:1000], elapsedSeconds=elapsed)
        return {"problem": pid, "status": "merge-failed", "elapsedSeconds": elapsed}

    try:
        res = subprocess.run(
            [
                str(PYTHON),
                str(MERGER),
                "--lang",
                "python",
                "--input",
                str(inp),
                "--out",
                str(merged),
                "--out-trees",
                str(trees),
            ],
            cwd=str(MERGER.parent),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        elapsed = round(time.monotonic() - started, 2)
        msg = (exc.stdout or "") if isinstance(exc.stdout, str) else ""
        log.write_text(msg + f"\nmerge timed out after {timeout}s; elapsed {elapsed}s\n")
        mark(pid, "merge-failed", error=f"merge timed out after {timeout}s", elapsedSeconds=elapsed)
        return {"problem": pid, "status": "merge-failed", "elapsedSeconds": elapsed}
    elapsed = round(time.monotonic() - started, 2)
    log.write_text(res.stdout)
    if res.returncode != 0 or not merged.exists():
        mark(pid, "merge-failed", error=res.stdout[-1000:], elapsedSeconds=elapsed)
        return {"problem": pid, "status": "merge-failed", "elapsedSeconds": elapsed}
    ok, err = compile_ok(merged)
    if not ok:
        mark(pid, "merge-failed", error=err, elapsedSeconds=elapsed)
        return {"problem": pid, "status": "merge-failed", "elapsedSeconds": elapsed}
    mark(pid, "merged", bytes=merged.stat().st_size, elapsedSeconds=elapsed)
    return {"problem": pid, "status": "merged", "elapsedSeconds": elapsed}


def gpt55_wrong_rows() -> list[dict]:
    rows = []
    for path in sorted(SUBMISSIONS.glob("manifest_gpt55*final_verdicts.json")):
        try:
            data = json.loads(path.read_text())
        except Exception:
            continue
        if not isinstance(data, list):
            continue
        for row in data:
            row = dict(row)
            row["_source"] = str(path.relative_to(ROOT))
            rows.append(row)
    by_pid = {}
    for row in rows:
        pid = row.get("problem")
        if not pid:
            continue
        old = by_pid.get(pid)
        if old is None or (row.get("creationTimeSeconds") or 0) >= (old.get("creationTimeSeconds") or 0):
            by_pid[pid] = row
    out = []
    for pid, row in by_pid.items():
        if row.get("submissionId") and row.get("verdict") in BAD_VERDICTS:
            out.append(row)
    return sorted(out, key=lambda r: r["problem"])


def load_meta_by_pid() -> dict[str, dict]:
    return {problem_id(problem): problem for problem in json.loads(META.read_text())}


def write_manifest(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(rows, indent=2))


def fetch_status(handle: str, count: int) -> list[dict]:
    url = f"https://codeforces.com/api/user.status?handle={handle}&from=1&count={count}"
    for attempt in range(8):
        try:
            with urllib.request.urlopen(url, timeout=30) as fh:
                payload = json.load(fh)
            if payload.get("status") == "OK":
                return payload["result"]
        except Exception:
            pass
        time.sleep(3 + attempt * 2)
    raise RuntimeError("Could not read Codeforces API")


def latest_for(problems: set[str], handle: str, lower_bound: int, count: int) -> dict[str, dict]:
    latest = {}
    for sub in fetch_status(handle, count):
        problem = sub["problem"]
        pid = f"{problem.get('contestId')}{problem.get('index')}"
        if pid in problems and sub.get("creationTimeSeconds", 0) >= lower_bound and pid not in latest:
            latest[pid] = sub
    return latest


def run_submit(manifest: Path, delay: int) -> list[dict]:
    cmd = ["node", str(SUBMITTER), "--delay", str(delay), str(manifest)]
    log_path = LOGS / f"submit_{manifest.stem}.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("w") as lf:
        proc = subprocess.Popen(
            cmd,
            cwd=str(ROOT),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            bufsize=1,
        )
        assert proc.stdout is not None
        for line in proc.stdout:
            print(line, end="", flush=True)
            lf.write(line)
            lf.flush()
        rc = proc.wait()
    if rc != 0:
        raise RuntimeError(f"submitter exited {rc}")
    return json.loads(manifest.with_name(manifest.stem + "_results.json").read_text())


def reconcile(entries: list[dict], submit_rows: list[dict], handle: str, run_started: int, api_count: int) -> dict:
    wanted = {x["problem"] for x in entries}
    errors = {x["problem"]: x.get("error") for x in submit_rows if x.get("status") == "error"}
    latest = {}
    for attempt in range(30):
        latest = latest_for(wanted, handle, run_started, api_count)
        pending = [
            pid for pid in wanted
            if pid not in latest or latest[pid].get("verdict") in (None, "TESTING")
        ]
        print(time.strftime("[%Y-%m-%d %H:%M:%S]"), f"API poll {attempt + 1}: matched {len(latest)}/{len(wanted)}, pending {len(pending)}", flush=True)
        if not pending:
            break
        time.sleep(20)
    rows = []
    by_entry = {x["problem"]: x for x in entries}
    for pid in sorted(wanted, key=lambda x: entries.index(by_entry[x])):
        entry = by_entry[pid]
        sub = latest.get(pid)
        if sub:
            label = LABELS.get(sub.get("verdict"), sub.get("verdict") or "submitted")
            rows.append({
                "problem": pid,
                "name": entry.get("name"),
                "rating": entry.get("rating"),
                "status": "submitted",
                "submitError": None,
                "submissionId": sub.get("id"),
                "creationTimeSeconds": sub.get("creationTimeSeconds"),
                "language": sub.get("programmingLanguage"),
                "verdict": sub.get("verdict"),
                "verdictLabel": label,
                "passedTestCount": sub.get("passedTestCount"),
                "timeMs": sub.get("timeConsumedMillis"),
            })
        else:
            err = errors.get(pid)
            status = "submit-error" if err else "unconfirmed"
            if err and "python language option" in err.lower():
                status = "unavailable-python"
            elif err and "no more than" in err.lower():
                status = "blocked-daily-limit"
            rows.append({
                "problem": pid,
                "name": entry.get("name"),
                "rating": entry.get("rating"),
                "status": status,
                "submitError": err,
                "submissionId": None,
                "creationTimeSeconds": None,
                "language": None,
                "verdict": None,
                "verdictLabel": status,
                "passedTestCount": None,
                "timeMs": None,
            })
    submitted = [r for r in rows if r.get("submissionId")]
    accepted = sum(r.get("verdict") == "OK" for r in submitted)
    return {
        "rows": rows,
        "submitted": len(submitted),
        "accepted": accepted,
        "notAccepted": len(submitted) - accepted,
        "counts": dict(Counter(r["verdictLabel"] for r in rows)),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default="gpt-5.5")
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--timeout", type=int, default=900)
    parser.add_argument("--merge-timeout", type=int, default=180)
    parser.add_argument("--limit", type=int)
    parser.add_argument("--only", nargs="*")
    parser.add_argument("--force-generate", action="store_true")
    parser.add_argument("--skip-generate", action="store_true")
    parser.add_argument("--skip-merge", action="store_true")
    parser.add_argument("--submit", action="store_true")
    parser.add_argument("--delay", type=int, default=35)
    parser.add_argument("--handle", default="__ParadigmShift")
    parser.add_argument("--api-count", type=int, default=2500)
    args = parser.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    meta = load_meta_by_pid()
    wrong = gpt55_wrong_rows()
    if args.only:
        wanted = set(args.only)
        wrong = [row for row in wrong if row["problem"] in wanted]
    if args.limit:
        wrong = wrong[: args.limit]
    (OUT / "one_shot_wrong_gpt55.json").write_text(json.dumps(wrong, indent=2))
    print(f"wrong one-shot python submissions: {len(wrong)}", flush=True)

    if not args.skip_generate:
        targets = [row["problem"] for row in wrong]
        progress = load_progress().get("problems", {})
        targets = [
            pid for pid in targets
            if args.force_generate or progress.get(pid, {}).get("status") not in {"generated", "merged"}
        ]
        done = 0
        failed = []
        with ThreadPoolExecutor(max_workers=args.workers) as pool:
            futures = [pool.submit(generate_candidates, meta[pid], args.model, args.timeout, args.force_generate) for pid in targets]
            for fut in as_completed(futures):
                rec = fut.result()
                done += 1
                if rec["status"] != "generated":
                    failed.append(rec["problem"])
                print(f"top5 progress: {done}/{len(targets)}; {rec['problem']}: {rec['status']}", flush=True)
        if failed:
            print("generate failed:", " ".join(failed), flush=True)

    if not args.skip_merge:
        merged = 0
        merge_failed = []
        progress = load_progress().get("problems", {})
        for row in wrong:
            pid = row["problem"]
            merged_path = OUT / pid / "merged.py"
            if progress.get(pid, {}).get("status") == "merged" and merged_path.exists():
                merged += 1
                print(f"merge progress: {merged}/{len(wrong)}; {pid}: cached", flush=True)
                continue
            if not all((OUT / pid / f"candidate_{i}.py").exists() for i in range(1, 6)):
                merge_failed.append(pid)
                continue
            rec = merge_one(pid, args.merge_timeout)
            if rec["status"] == "merged":
                merged += 1
            else:
                merge_failed.append(pid)
            print(f"merge progress: {merged}/{len(wrong)}; {pid}: {rec['status']}", flush=True)
        if merge_failed:
            print("merge failed:", " ".join(merge_failed), flush=True)

    entries = []
    for row in wrong:
        pid = row["problem"]
        merged = OUT / pid / "merged.py"
        if merged.exists():
            entries.append({
                "problem": pid,
                "path": str(merged.relative_to(ROOT)),
                "rating": row.get("rating") or meta.get(pid, {}).get("rating"),
                "name": row.get("name") or meta.get(pid, {}).get("name"),
                "oneShotVerdict": row.get("verdict"),
                "oneShotPassedTestCount": row.get("passedTestCount"),
            })
    manifest = SUBMISSIONS / "manifest_ast_merger_gpt55_wrongs.json"
    write_manifest(entries, manifest)
    print(f"merged manifest entries: {len(entries)} -> {manifest.relative_to(ROOT)}", flush=True)

    if args.submit:
        run_started = int(time.time()) - 120
        submit_rows = run_submit(manifest, args.delay)
        summary = reconcile(entries, submit_rows, args.handle, run_started, args.api_count)
        verdict_path = SUBMISSIONS / "manifest_ast_merger_gpt55_wrongs_final_verdicts.json"
        summary_path = SUBMISSIONS / "manifest_ast_merger_gpt55_wrongs_summary.json"
        verdict_path.write_text(json.dumps(summary["rows"], indent=2))
        summary_path.write_text(json.dumps({k: v for k, v in summary.items() if k != "rows"}, indent=2))
        print(
            f"FINAL: accepted {summary['accepted']}/{summary['submitted']}; "
            f"not accepted {summary['notAccepted']}/{summary['submitted']}; counts {summary['counts']}",
            flush=True,
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
