#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
import sys
import tempfile
import time
import urllib.request
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
META = ROOT / "codeforces" / "codeforces_data" / "problems_meta.json"
STATEMENTS = ROOT / "codeforces" / "codeforces_data" / "statements"
OUT = ROOT / "ast_merger_gpt"
SUBMISSIONS = ROOT / "submissions"
LOGS = ROOT / "logs"
MERGER = ROOT / "ast_merger_lang_agnostic" / "evaluate_clauses.py"
SUBMITTER = ROOT / "scripts" / "submit_batch_codeforces.mjs"
PYTHON = ROOT / ".venv" / "bin" / "python"
if not PYTHON.exists():
    PYTHON = Path(sys.executable)

CODE_BLOCK = re.compile(r"```(?:python|py)?\s*\n(.*?)```", re.DOTALL | re.I)
CLAUSE_MARKER = re.compile(r"^\s*#\s*CLAUSE:\s*([a-z][a-z0-9_]{2,40})\s*$", re.I | re.M)
BAD_TEXT = re.compile(
    r"(?i)(Generated by|pipeline-generated|#\s*todo|todo\b|fixme\b|stub\b|"
    r"placeholder\b|left\s+to\s+implement|implement\s+me|not\s+implemented)"
)
LABELS = {
    "OK": "Accepted",
    "WRONG_ANSWER": "Wrong answer",
    "TIME_LIMIT_EXCEEDED": "Time limit exceeded",
    "MEMORY_LIMIT_EXCEEDED": "Memory limit exceeded",
    "RUNTIME_ERROR": "Runtime error",
    "COMPILATION_ERROR": "Compilation error",
    "IDLENESS_LIMIT_EXCEEDED": "Idleness limit exceeded",
    "PARTIAL": "Partial",
    "TESTING": "Testing",
}


def pid(problem: dict) -> str:
    return f"{problem['contestId']}{problem['index']}"


def parse_pid(problem_id: str) -> tuple[str, str]:
    match = re.fullmatch(r"(\d+)([A-Za-z]\d*)", problem_id)
    if not match:
        raise ValueError(f"bad problem id: {problem_id}")
    return match.group(1), match.group(2).upper()


def statement_path(problem: dict) -> Path:
    return STATEMENTS / f"{problem['contestId']}_{problem['index']}.json"


def load_statement(problem: dict) -> dict:
    return json.loads(statement_path(problem).read_text())


def samples_for_pid(problem_id: str) -> list[dict]:
    contest, index = parse_pid(problem_id)
    path = STATEMENTS / f"{contest}_{index}.json"
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text())
    except Exception:
        return []
    return [s for s in data.get("samples", []) if "input" in s and "output" in s]


def statement_text(problem: dict) -> str:
    data = load_statement(problem)
    samples = "\n\n".join(
        f"Sample {i} input:\n{s.get('input', '')}\nSample {i} output:\n{s.get('output', '')}"
        for i, s in enumerate(data.get("samples", []), 1)
    )
    return f"""Problem id: {pid(problem)}
Title: {data.get("title") or problem["name"]}
Rating: {problem.get("rating", "unknown")}
Tags: {", ".join(problem.get("tags", []))}
Time limit: {data.get("time_limit", "unknown")}
Memory limit: {data.get("mem_limit", "unknown")}

Statement:
{data.get("statement", "")}

Input:
{data.get("input_spec", "")}

Output:
{data.get("output_spec", "")}

Samples:
{samples or "(none)"}
"""


def decomposition_prompt(problem: dict) -> str:
    return f"""Create an implementation decomposition for this Codeforces problem before any code is written.

Return only markdown with exactly these sections:
1. `Clause IDs`: 5 to 8 snake_case identifiers, each on its own bullet.
2. `Clause Responsibilities`: one bullet per id, explaining the exact algorithmic role.
3. `Shared Algorithm`: the common paradigm every implementation must use.
4. `Allowed Variation`: local implementation differences that keep the same paradigm and similar modularity.

The clauses must be real algorithmic sections, not shallow labels like main/read_input/solve.
Good clause examples are: normalize_constraints, build_transition_state, process_component_stack,
compute_prefix_invariants, greedy_exchange_step, reconstruct_answer.

{statement_text(problem)}
"""


def codegen_prompt(problem: dict, decomposition: str) -> str:
    return f"""Write five independent complete Python 3 / PyPy 3 programs for this Codeforces problem.

You must follow this pre-written decomposition exactly:
{decomposition}

Hard constraints:
- All five programs must use the same high-level algorithmic paradigm and similar modularity.
- They must differ in real implementation structure, expression choices, boundary handling, loop organization,
  helper factoring, or data representation. Mere variable renaming is not enough.
- Do not make one recursive and another iterative unless the decomposition explicitly allows it.
- Do not use classes unless all five use the same class-level structure.
- Each program must contain the same `# CLAUSE: <id>` marker lines, in the same order, using the Clause IDs above.
- Every marker must introduce a meaningful section of code for that clause.
- Use standard input/output only. No explanations, prompts, TODOs, placeholders, or comments except CLAUSE markers.
- Return exactly five fenced python code blocks and nothing else.

{statement_text(problem)}
"""


def call_codex(prompt: str, model: str, timeout: int) -> str:
    with tempfile.NamedTemporaryFile(prefix="codex_batch_", suffix=".md", delete=False) as fh:
        out = Path(fh.name)
    try:
        res = subprocess.run(
            [
                "codex",
                "exec",
                "--model",
                model,
                "--cd",
                str(ROOT),
                "--sandbox",
                "read-only",
                "--dangerously-bypass-approvals-and-sandbox",
                "--output-last-message",
                str(out),
                prompt,
            ],
            cwd=str(ROOT),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=timeout,
            check=False,
        )
        if res.returncode != 0:
            detail = (res.stderr.strip() or res.stdout.strip())[-1200:]
            raise RuntimeError(f"codex exit {res.returncode}: {detail}")
        return out.read_text(errors="replace")
    finally:
        out.unlink(missing_ok=True)


def extract_five(text: str) -> list[str]:
    blocks = [b.strip() + "\n" for b in CODE_BLOCK.findall(text)]
    if len(blocks) != 5:
        raise RuntimeError(f"expected 5 python code blocks, got {len(blocks)}")
    return blocks


def compile_ok(path: Path) -> tuple[bool, str]:
    res = subprocess.run(
        [str(PYTHON), "-m", "py_compile", str(path)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    return res.returncode == 0, res.stderr.strip()[-1000:]


def structural_signature(code: str) -> str:
    tree = ast.parse(code)
    for node in ast.walk(tree):
        if isinstance(node, ast.Name):
            node.id = "ID"
        elif isinstance(node, ast.arg):
            node.arg = "ARG"
        elif isinstance(node, ast.Constant):
            node.value = "LIT"
    return ast.dump(tree, annotate_fields=False, include_attributes=False)


def marker_ids(code: str) -> list[str]:
    return [m.group(1).lower() for m in CLAUSE_MARKER.finditer(code)]


def validate_candidates(pdir: Path, codes: list[str]) -> tuple[bool, str]:
    if len({c.strip() for c in codes}) != len(codes):
        return False, "duplicate candidate code"
    markers = [marker_ids(code) for code in codes]
    if any(len(m) < 5 for m in markers):
        return False, f"not enough clause markers: {[len(m) for m in markers]}"
    if len({tuple(m) for m in markers}) != 1:
        return False, f"candidate clause markers differ: {markers}"
    signatures = []
    for i, code in enumerate(codes, 1):
        if BAD_TEXT.search(code):
            return False, f"candidate {i}: bad marker text"
        path = pdir / f"candidate_{i}.py"
        path.write_text(code)
        ok, err = compile_ok(path)
        if not ok:
            return False, f"candidate {i}: {err}"
        signatures.append(structural_signature(code))
    if len(set(signatures)) < 2:
        return False, "all candidates are structurally identical after name/literal normalization"
    return True, ""


def run_on_samples(path: Path, samples: list[dict], timeout: int = 5) -> dict:
    if not samples:
        return {"ok": True, "passed": 0, "total": 0, "reason": "no samples"}
    ok, err = compile_ok(path)
    if not ok:
        return {"ok": False, "passed": 0, "total": len(samples), "reason": err or "compile failed"}
    passed = 0
    for i, sample in enumerate(samples, 1):
        try:
            res = subprocess.run(
                [str(PYTHON), str(path)],
                input=sample.get("input") or "",
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=timeout,
                check=False,
            )
        except subprocess.TimeoutExpired:
            return {"ok": False, "passed": passed, "total": len(samples), "reason": f"sample {i} timed out"}
        if res.returncode != 0:
            return {"ok": False, "passed": passed, "total": len(samples), "reason": f"sample {i} runtime error"}
        if res.stdout.strip() != (sample.get("output") or "").strip():
            return {"ok": False, "passed": passed, "total": len(samples), "reason": f"sample {i} wrong answer"}
        passed += 1
    return {"ok": True, "passed": passed, "total": len(samples), "reason": "passed samples"}


def split_clauses(code: str) -> list[dict]:
    matches = list(CLAUSE_MARKER.finditer(code))
    clauses = []
    prefix = code[:matches[0].start()].strip()
    for i, match in enumerate(matches):
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(code)
        body = code[start:end].strip("\n")
        section = ((prefix + "\n\n") if i == 0 and prefix else "") + body
        clauses.append({
            "clause_id": match.group(1).lower(),
            "signature": "python_section",
            "code": section.rstrip() + "\n",
        })
    return clauses


def build_uast_input(problem_id: str) -> Path:
    pdir = OUT / problem_id
    samples = samples_for_pid(problem_id)
    passing = []
    all_candidates = []
    filter_rows = []
    for i in range(1, 6):
        path = pdir / f"candidate_{i}.py"
        all_candidates.append((i, path.read_text()))
        result = run_on_samples(path, samples)
        filter_rows.append({"candidate": i, **result})
        if result["ok"]:
            passing.append((i, path.read_text()))
    selected = passing if passing or not samples else all_candidates
    sample_gate = "passing_only"
    if not samples:
        sample_gate = "no_samples_all_candidates"
    elif not passing:
        sample_gate = "fallback_all_candidates"
    (pdir / "sample_filter.json").write_text(json.dumps({
        "samples": len(samples),
        "selectedCandidates": [i for i, _ in selected],
        "passingCandidates": [i for i, _ in passing],
        "sampleGate": sample_gate,
        "results": filter_rows,
    }, indent=2))

    programs = [{"id": f"P{i}", "clauses": split_clauses(code)} for i, code in selected]
    out = pdir / "uast_input.json"
    out.write_text(json.dumps({"programs": programs}, indent=2))
    return out


def sample_passing_candidate_ids(problem_id: str) -> list[int]:
    path = OUT / problem_id / "sample_filter.json"
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text())
    except Exception:
        return []
    return [int(i) for i in data.get("selectedCandidates", [])]


def build_whole_program_uast_input(problem_id: str, candidate_ids: list[int]) -> Path:
    pdir = OUT / problem_id
    programs = []
    for i in candidate_ids:
        source = (pdir / f"candidate_{i}.py").read_text()
        programs.append({
            "id": f"P{i}",
            "clauses": [
                {
                    "clause_id": "program",
                    "signature": "python_module",
                    "code": source if source.endswith("\n") else source + "\n",
                }
            ],
        })
    out = pdir / "uast_input_whole_program_fallback.json"
    out.write_text(json.dumps({"programs": programs}, indent=2))
    return out


def whole_program_fallback_merge(problem_id: str, timeout: int, reason: str, elapsed_so_far: float) -> dict:
    pdir = OUT / problem_id
    candidate_ids = sample_passing_candidate_ids(problem_id)
    if not candidate_ids:
        return {
            "problem": problem_id,
            "status": "merge-failed",
            "elapsedSeconds": elapsed_so_far,
            "error": reason,
        }

    started = time.monotonic()
    inp = build_whole_program_uast_input(problem_id, candidate_ids)
    merged = pdir / "merged.py"
    res = subprocess.run(
        [
            str(PYTHON),
            str(MERGER),
            "--lang",
            "python",
            "--input",
            str(inp),
            "--out",
            str(merged),
        ],
        cwd=str(MERGER.parent),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=max(1, timeout),
        check=False,
    )
    elapsed = round(elapsed_so_far + time.monotonic() - started, 2)
    fallback_log = pdir / "merge_fallback.log"
    fallback_log.write_text(f"fallback reason: {reason}\n\n{res.stdout}")
    if res.returncode != 0 or not merged.exists():
        return {
            "problem": problem_id,
            "status": "merge-failed",
            "elapsedSeconds": elapsed,
            "error": f"{reason}; whole-program fallback failed",
        }
    ok, err = compile_ok(merged)
    if not ok:
        return {
            "problem": problem_id,
            "status": "merge-failed",
            "elapsedSeconds": elapsed,
            "error": f"{reason}; whole-program fallback compile failed: {err}",
        }
    conf = None
    match = re.search(r"Average Confidence:\s*([0-9.]+)", res.stdout)
    if match:
        conf = float(match.group(1))
    return {
        "problem": problem_id,
        "status": "merged-fallback",
        "elapsedSeconds": elapsed,
        "confidence": conf,
        "fallback": "whole-program",
        "fallbackReason": reason,
        "selectedCandidates": candidate_ids,
    }


def generate_problem(problem: dict, model: str, timeout: int, force: bool) -> dict:
    problem_id = pid(problem)
    pdir = OUT / problem_id
    pdir.mkdir(parents=True, exist_ok=True)
    if not force and all((pdir / f"candidate_{i}.py").exists() for i in range(1, 6)) and (pdir / "decomposition.md").exists():
        return {"problem": problem_id, "status": "cached"}
    last_error = ""
    for attempt in range(1, 4):
        try:
            decomposition = call_codex(decomposition_prompt(problem), model, timeout)
            (pdir / "decomposition.md").write_text(decomposition)
            raw = call_codex(codegen_prompt(problem, decomposition), model, timeout)
            (pdir / "top5_raw.md").write_text(raw)
            codes = extract_five(raw)
            ok, err = validate_candidates(pdir, codes)
            if not ok:
                raise RuntimeError(err)
            return {"problem": problem_id, "status": "generated", "attempt": attempt}
        except Exception as exc:
            last_error = str(exc)
            (pdir / "generate_error.txt").write_text(last_error)
            time.sleep(5 * attempt)
    return {"problem": problem_id, "status": "generate-failed", "error": last_error}


def merge_problem(problem_id: str, timeout: int) -> dict:
    pdir = OUT / problem_id
    merged = pdir / "merged.py"
    log = pdir / "merge.log"
    trees = pdir / "trees.txt"
    started = time.monotonic()
    try:
        inp = build_uast_input(problem_id)
        res = subprocess.run(
            [
                str(PYTHON),
                str(MERGER),
                "--lang",
                "python",
                "--input",
                str(inp),
                "--out",
                str(merged),
                "--out-trees",
                str(trees),
            ],
            cwd=str(MERGER.parent),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        elapsed = round(time.monotonic() - started, 2)
        msg = (exc.stdout or "") if isinstance(exc.stdout, str) else ""
        log.write_text(msg + f"\nmerge timed out after {timeout}s; elapsed {elapsed}s\n")
        return {"problem": problem_id, "status": "merge-failed", "elapsedSeconds": elapsed, "error": "timeout"}
    except Exception as exc:
        elapsed = round(time.monotonic() - started, 2)
        log.write_text(str(exc) + "\n")
        return {"problem": problem_id, "status": "merge-failed", "elapsedSeconds": elapsed, "error": str(exc)}
    elapsed = round(time.monotonic() - started, 2)
    log.write_text(res.stdout)
    if res.returncode != 0 or not merged.exists():
        return whole_program_fallback_merge(problem_id, max(1, timeout - int(elapsed)), res.stdout[-1000:], elapsed)
    ok, err = compile_ok(merged)
    if not ok:
        return whole_program_fallback_merge(problem_id, max(1, timeout - int(elapsed)), err, elapsed)
    conf = None
    match = re.search(r"Average Confidence:\s*([0-9.]+)", res.stdout)
    if match:
        conf = float(match.group(1))
    return {"problem": problem_id, "status": "merged", "elapsedSeconds": elapsed, "confidence": conf}


def fetch_status(handle: str, count: int) -> list[dict]:
    url = f"https://codeforces.com/api/user.status?handle={handle}&from=1&count={count}"
    for attempt in range(8):
        try:
            with urllib.request.urlopen(url, timeout=30) as fh:
                payload = json.load(fh)
            if payload.get("status") == "OK":
                return payload["result"]
        except Exception:
            pass
        time.sleep(3 + 2 * attempt)
    raise RuntimeError("Could not read Codeforces API")


def reconcile(entries: list[dict], submit_rows: list[dict], handle: str, run_started: int, api_count: int) -> dict:
    wanted = {x["problem"] for x in entries}
    errors = {x["problem"]: x.get("error") for x in submit_rows if x.get("status") == "error"}
    latest = {}
    for _ in range(30):
        latest = {}
        for sub in fetch_status(handle, api_count):
            problem = sub["problem"]
            problem_id = f"{problem.get('contestId')}{problem.get('index')}"
            if problem_id in wanted and sub.get("creationTimeSeconds", 0) >= run_started and problem_id not in latest:
                latest[problem_id] = sub
        pending = [p for p in wanted if p not in latest or latest[p].get("verdict") in (None, "TESTING")]
        if not pending:
            break
        time.sleep(20)
    rows = []
    for entry in entries:
        problem_id = entry["problem"]
        sub = latest.get(problem_id)
        if sub:
            verdict = sub.get("verdict")
            rows.append({
                **entry,
                "status": "submitted",
                "submissionId": sub.get("id"),
                "creationTimeSeconds": sub.get("creationTimeSeconds"),
                "language": sub.get("programmingLanguage"),
                "verdict": verdict,
                "verdictLabel": LABELS.get(verdict, verdict or "submitted"),
                "passedTestCount": sub.get("passedTestCount"),
                "timeMs": sub.get("timeConsumedMillis"),
            })
        else:
            err = errors.get(problem_id)
            rows.append({
                **entry,
                "status": "submit-error" if err else "unconfirmed",
                "submitError": err,
                "submissionId": None,
                "verdict": None,
                "verdictLabel": "submit-error" if err else "unconfirmed",
            })
    counts = dict(Counter(r["verdictLabel"] for r in rows))
    submitted = [r for r in rows if r.get("submissionId")]
    accepted = sum(r.get("verdict") == "OK" for r in submitted)
    return {"rows": rows, "submitted": len(submitted), "accepted": accepted, "counts": counts}


def run_submit(manifest: Path, delay: int) -> list[dict]:
    cmd = ["node", str(SUBMITTER), "--delay", str(delay), str(manifest)]
    res = subprocess.run(cmd, cwd=str(ROOT), text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False)
    (LOGS / f"submit_{manifest.stem}.log").write_text(res.stdout)
    if res.returncode != 0:
        raise RuntimeError(f"submitter exited {res.returncode}: {res.stdout[-1000:]}")
    return json.loads(manifest.with_name(manifest.stem + "_results.json").read_text())


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default="gpt-5.5")
    parser.add_argument("--start", type=int, default=0)
    parser.add_argument("--batch-size", type=int, default=20)
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--gen-timeout", type=int, default=1200)
    parser.add_argument("--merge-timeout", type=int, default=300)
    parser.add_argument("--force-generate", action="store_true")
    parser.add_argument("--submit", action="store_true")
    parser.add_argument("--delay", type=int, default=35)
    parser.add_argument("--handle", default="__ParadigmShift")
    parser.add_argument("--api-count", type=int, default=2500)
    args = parser.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    LOGS.mkdir(parents=True, exist_ok=True)
    SUBMISSIONS.mkdir(parents=True, exist_ok=True)
    meta = json.loads(META.read_text())
    batch = [p for p in meta[args.start: args.start + args.batch_size] if statement_path(p).exists()]
    batch_id = f"{args.start + 1:04d}_{args.start + len(batch):04d}"
    print(f"batch {batch_id}: {len(batch)} problems", flush=True)

    gen_rows = []
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = [pool.submit(generate_problem, p, args.model, args.gen_timeout, args.force_generate) for p in batch]
        for fut in as_completed(futures):
            rec = fut.result()
            gen_rows.append(rec)
            print(f"generate {len(gen_rows)}/{len(batch)} {rec['problem']}: {rec['status']}", flush=True)

    merge_rows = []
    for problem in batch:
        problem_id = pid(problem)
        if not all((OUT / problem_id / f"candidate_{i}.py").exists() for i in range(1, 6)):
            merge_rows.append({"problem": problem_id, "status": "merge-skipped"})
            continue
        rec = merge_problem(problem_id, args.merge_timeout)
        merge_rows.append(rec)
        print(f"merge {len(merge_rows)}/{len(batch)} {problem_id}: {rec['status']} {rec.get('elapsedSeconds')}s conf={rec.get('confidence')}", flush=True)

    entries = []
    by_merge = {r["problem"]: r for r in merge_rows}
    for problem in batch:
        problem_id = pid(problem)
        rec = by_merge.get(problem_id, {})
        if rec.get("status") == "merged":
            entries.append({
                "problem": problem_id,
                "path": str((OUT / problem_id / "merged.py").relative_to(ROOT)),
                "rating": problem.get("rating"),
                "name": problem.get("name"),
                "confidence": rec.get("confidence"),
            })
    manifest = SUBMISSIONS / f"manifest_ast_merger_gpt_batch_{batch_id}.json"
    manifest.write_text(json.dumps(entries, indent=2))

    summary = {
        "batch": batch_id,
        "start": args.start,
        "batchSize": len(batch),
        "generated": gen_rows,
        "merged": merge_rows,
        "manifest": str(manifest.relative_to(ROOT)),
        "manifestEntries": len(entries),
        "avgConfidence": (
            sum(r["confidence"] for r in merge_rows if r.get("confidence") is not None)
            / max(1, sum(1 for r in merge_rows if r.get("confidence") is not None))
        ),
    }

    if args.submit and entries:
        run_started = int(time.time()) - 120
        submit_rows = run_submit(manifest, args.delay)
        verdicts = reconcile(entries, submit_rows, args.handle, run_started, args.api_count)
        verdict_path = SUBMISSIONS / f"manifest_ast_merger_gpt_batch_{batch_id}_final_verdicts.json"
        verdict_path.write_text(json.dumps(verdicts["rows"], indent=2))
        summary["submitted"] = verdicts["submitted"]
        summary["accepted"] = verdicts["accepted"]
        summary["accuracy"] = verdicts["accepted"] / max(1, verdicts["submitted"])
        summary["verdictCounts"] = verdicts["counts"]
        summary["verdicts"] = str(verdict_path.relative_to(ROOT))

    summary_path = OUT / f"batch_{batch_id}_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2))
    print(f"summary: {summary_path.relative_to(ROOT)}", flush=True)
    print(f"merged {len(entries)}/{len(batch)} avg_conf={summary['avgConfidence']:.4f}", flush=True)
    if "submitted" in summary:
        print(f"accepted {summary['accepted']}/{summary['submitted']} accuracy={summary['accuracy']:.2%} counts={summary['verdictCounts']}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
