#!/usr/bin/env python3
from __future__ import annotations

import ast
import argparse
import json
import re
import subprocess
import time
import urllib.request
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
META = ROOT / "codeforces" / "codeforces_data" / "problems_meta.json"
SOL = ROOT / "sonnet_gen"
SUBMISSIONS = ROOT / "submissions"
LOGS = ROOT / "logs"
SUBMITTER = ROOT / "scripts" / "submit_batch_codeforces.mjs"

LABELS = {
    "OK": "Accepted",
    "WRONG_ANSWER": "Wrong answer",
    "TIME_LIMIT_EXCEEDED": "Time limit exceeded",
    "MEMORY_LIMIT_EXCEEDED": "Memory limit exceeded",
    "RUNTIME_ERROR": "Runtime error",
    "COMPILATION_ERROR": "Compilation error",
    "IDLENESS_LIMIT_EXCEEDED": "Idleness limit exceeded",
    "PARTIAL": "Partial",
    "TESTING": "Testing",
}

BAD_MARKER = re.compile(
    r"(?i)(Generated by|Paradigm:|Rating:.*Tags:|pipeline-generated|"
    r"tail_recursion|search_tree|greedy_recursion|#\s*todo|todo\b|fixme\b|"
    r"stub\b|placeholder\b|left\s+to\s+implement|implement\s+me|not\s+implemented)"
)


def log(msg: str) -> None:
    print(time.strftime("[%Y-%m-%d %H:%M:%S]"), msg, flush=True)


def pid(problem: dict) -> str:
    return f"{problem['contestId']}{problem['index']}"


def is_clean_solution(path: Path) -> bool:
    if not path.exists():
        return False
    text = path.read_text(errors="replace")
    if BAD_MARKER.search(text):
        return False
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return False
    if any(isinstance(node, ast.Pass) for node in ast.walk(tree)):
        return False
    calls = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            func = node.func
            if isinstance(func, ast.Name):
                calls.append(func.id)
            elif isinstance(func, ast.Attribute):
                calls.append(func.attr)
    return any(name in {"print", "write"} for name in calls)


def previous_sonnet_state(problem_ids: set[str]) -> tuple[set[str], set[str]]:
    submitted = set()
    unavailable = set()
    for path in sorted(SUBMISSIONS.glob("manifest_sonnet*.json")):
        try:
            data = json.loads(path.read_text())
        except Exception:
            continue
        if not isinstance(data, list):
            continue
        for row in data:
            name = row.get("problem")
            if name in problem_ids and (row.get("submissionId") or row.get("status") == "submitted"):
                submitted.add(name)
            if name in problem_ids and (
                row.get("status") == "unavailable-python"
                or row.get("verdictLabel") == "unavailable-python"
            ):
                unavailable.add(name)
    return submitted, unavailable


def fetch_status(handle: str, count: int) -> list[dict]:
    url = f"https://codeforces.com/api/user.status?handle={handle}&from=1&count={count}"
    for attempt in range(8):
        try:
            with urllib.request.urlopen(url, timeout=30) as fh:
                payload = json.load(fh)
            if payload.get("status") == "OK":
                return payload["result"]
        except Exception:
            pass
        time.sleep(3 + attempt * 2)
    raise RuntimeError("Could not fetch Codeforces user.status")


def latest_for(problems: set[str], handle: str, lower_bound: int, count: int) -> dict[str, dict]:
    latest = {}
    for sub in fetch_status(handle, count):
        problem = sub["problem"]
        name = f"{problem.get('contestId')}{problem.get('index')}"
        if name in problems and sub.get("creationTimeSeconds", 0) >= lower_bound and name not in latest:
            latest[name] = sub
    return latest


def write_manifest(entries: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(entries, indent=2))


def run_submit(manifest: Path, delay: int, log_path: Path) -> list[dict]:
    cmd = ["node", str(SUBMITTER), "--delay", str(delay), str(manifest)]
    log(f"Running: {' '.join(cmd)}")
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("w") as lf:
        proc = subprocess.Popen(
            cmd,
            cwd=str(ROOT),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            bufsize=1,
        )
        assert proc.stdout is not None
        for line in proc.stdout:
            print(line, end="", flush=True)
            lf.write(line)
            lf.flush()
        rc = proc.wait()
    if rc != 0:
        raise RuntimeError(f"submitter exited {rc}: {manifest}")
    return json.loads(manifest.with_name(manifest.stem + "_results.json").read_text())


def is_daily_limit(row: dict) -> bool:
    return "no more than" in (row.get("error") or "").lower()


def build_rows(entries: list[dict], latest: dict[str, dict], errors: dict[str, str]) -> list[dict]:
    rows = []
    for entry in entries:
        name = entry["problem"]
        sub = latest.get(name)
        error = errors.get(name)
        if sub:
            label = LABELS.get(sub.get("verdict"), sub.get("verdict") or "submitted")
            rows.append({**entry, "status": "submitted", "submitError": None, "submissionId": sub.get("id"),
                         "creationTimeSeconds": sub.get("creationTimeSeconds"),
                         "language": sub.get("programmingLanguage"), "verdict": sub.get("verdict"),
                         "verdictLabel": label, "passedTestCount": sub.get("passedTestCount"),
                         "timeMs": sub.get("timeConsumedMillis")})
        elif error and "python language option" in error.lower():
            rows.append({**entry, "status": "unavailable-python", "submitError": error,
                         "submissionId": None, "verdict": None, "verdictLabel": "unavailable-python"})
        elif error and "same code" in error.lower():
            rows.append({**entry, "status": "rejected", "submitError": error,
                         "submissionId": None, "verdict": None, "verdictLabel": "rejected"})
        elif error and "no more than" in error.lower():
            rows.append({**entry, "status": "blocked-daily-limit", "submitError": error,
                         "submissionId": None, "verdict": None, "verdictLabel": "blocked-daily-limit"})
        elif error:
            rows.append({**entry, "status": "submit-error", "submitError": error,
                         "submissionId": None, "verdict": None, "verdictLabel": "submit-error"})
        else:
            rows.append({**entry, "status": "unconfirmed", "submitError": None,
                         "submissionId": None, "verdict": None, "verdictLabel": "unconfirmed"})
    return rows


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", type=int, default=250)
    parser.add_argument("--chunk-size", type=int, default=35)
    parser.add_argument("--delay", type=int, default=35)
    parser.add_argument("--handle", default="__ParadigmShift")
    parser.add_argument("--api-count", type=int, default=2000)
    parser.add_argument("--prefix", default="sonnet_clean_first250")
    args = parser.parse_args()

    run_started = int(time.time()) - 120
    meta = json.loads(META.read_text())
    all_ids = {pid(problem) for problem in meta}
    already, unavailable_previous = previous_sonnet_state(all_ids)

    candidates = []
    skipped_bad = []
    for problem in meta:
        name = pid(problem)
        if name in already or name in unavailable_previous:
            continue
        path = SOL / name / "solution.py"
        if not path.exists():
            continue
        if not is_clean_solution(path):
            skipped_bad.append(name)
            continue
        candidates.append({"problem": name, "path": str(path.relative_to(ROOT)),
                           "rating": problem.get("rating"), "name": problem["name"]})

    if len(candidates) < args.target:
        raise RuntimeError(f"only {len(candidates)} clean unsubmitted Sonnet candidates")

    candidate_by_pid = {entry["problem"]: entry for entry in candidates}
    processed = set()
    errors = {}
    submitted_pids = set()
    chunk_no = 0
    cursor = 0
    daily_blocked = False

    log(f"Sonnet candidates: {len(candidates)} clean unsubmitted; skipped bad {len(skipped_bad)}")
    while len(submitted_pids) < args.target and cursor < len(candidates) and not daily_blocked:
        chunk = []
        while cursor < len(candidates) and len(chunk) < args.chunk_size:
            entry = candidates[cursor]
            cursor += 1
            if entry["problem"] in processed or entry["problem"] in submitted_pids:
                continue
            chunk.append(entry)
        if not chunk:
            continue
        chunk_no += 1
        manifest = SUBMISSIONS / f"manifest_{args.prefix}_chunk{chunk_no:02d}.json"
        write_manifest(chunk, manifest)
        results = run_submit(manifest, args.delay, LOGS / f"submit_{args.prefix}_chunk{chunk_no:02d}.log")
        processed.update(row["problem"] for row in results)
        for row in results:
            if row.get("status") == "error":
                errors[row["problem"]] = row.get("error", "")
                if is_daily_limit(row):
                    daily_blocked = True

        wanted_now = set(submitted_pids) | {r["problem"] for r in results if r.get("status") == "submitted"}
        for _ in range(18):
            latest = latest_for(wanted_now | set(candidate_by_pid), args.handle, run_started, args.api_count)
            submitted_pids = set(latest)
            pending = [name for name in wanted_now if name not in latest or latest[name].get("verdict") in (None, "TESTING")]
            log(f"Chunk {chunk_no}: API-visible {len(submitted_pids)}/{args.target}, pending {len(pending)}")
            if not pending:
                break
            time.sleep(20)
        included = set(processed) | submitted_pids
        rows = build_rows([e for e in candidates if e["problem"] in included], latest, errors)
        live = SUBMISSIONS / f"manifest_{args.prefix}_live_verdicts.json"
        live.write_text(json.dumps(rows, indent=2))
        accepted = sum(1 for row in rows if row.get("verdict") == "OK")
        not_accepted = sum(1 for row in rows if row.get("submissionId") and row.get("verdict") != "OK")
        counts = Counter(row["verdictLabel"] for row in rows)
        log(f"Live summary: accepted {accepted}/{len(submitted_pids)}, not accepted {not_accepted}/{len(submitted_pids)}, "
            f"unavailable {counts.get('unavailable-python', 0)}, daily-blocked {counts.get('blocked-daily-limit', 0)}")

    final_latest = latest_for(set(candidate_by_pid), args.handle, run_started, args.api_count)
    submitted_pids = set(final_latest)
    included = set(processed) | submitted_pids
    rows = build_rows([e for e in candidates if e["problem"] in included], final_latest, errors)
    out = SUBMISSIONS / f"manifest_{args.prefix}_final_verdicts.json"
    out.write_text(json.dumps(rows, indent=2))
    submitted = [row for row in rows if row.get("submissionId")]
    accepted = sum(1 for row in submitted if row.get("verdict") == "OK")
    counts = Counter(row["verdictLabel"] for row in rows)
    summary = {"target": args.target, "submitted": len(submitted), "accepted": accepted,
               "notAccepted": len(submitted) - accepted, "counts": dict(counts),
               "output": str(out.relative_to(ROOT))}
    summary_path = SUBMISSIONS / f"manifest_{args.prefix}_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2))
    log(f"FINAL: accepted {summary['accepted']}/{summary['submitted']}, not accepted {summary['notAccepted']}/{summary['submitted']}")
    log(f"Wrote {out.relative_to(ROOT)} and {summary_path.relative_to(ROOT)}")
    return 0 if len(submitted) >= args.target else 1


if __name__ == "__main__":
    raise SystemExit(main())
